server.port     : ":8000"
server.api_key  : "kmzway87aa"
server.database : "mysql"

mysql.host      : "192.168.40.17"
mysql.port      : "3306"
mysql.database  : "prueba_tecnica_velocity"
mysql.username  : "root"
mysql.password  : "root"
