server.port     : ":8000"
server.api_key  : "kmzway87aa"
server.database : "mysql"

mysql.host      : "127.0.0.1"
mysql.port      : "3306"
mysql.database  : ""
mysql.username  : ""
mysql.password  : ""